Tours/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ToursApp.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

ToursApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home.as_view(),name='home'),
    path('register/',views.register.as_view(),name='register'),
    path('signin/',views.signin.as_view(),name='signin'),
    path('aboutus/',views.aboutus.as_view(),name='aboutus'),
    path('signout/',views.signout.as_view(),name='signout'),
    path('destination/',views.destination.as_view(),name='destination'),
    path('viewdetail/<slug:tour_id>',views.viewdetail.as_view(),name='viewdetail'),
    path('profile/<slug:username>',views.profile.as_view(),name='profile'),
    path('searches/',views.searches.as_view(),name='searches'),
    path('booking/',views.booking.as_view(),name='booking'),
    path('mytrips/',views.mytrips.as_view(),name='mytrips'),
    path('cancelbook/<slug:bookid>',views.cancelbook.as_view(),name='cancelbook'),
    path('state/<slug:destination>',views.state.as_view(),name='state'),
    path('tripstory/',views.tripstory.as_view(),name='tripstory'),
    path('contactus/',views.contactus.as_view(),name='contactus'),
    path('viewbooking/<slug:tour_id>',views.viewbooking.as_view(),name='viewbooking'),


    # admin url
    path('checkbook/',views.checkbook.as_view(),name='checkbook'),
    path('uploadtrip/',views.uploadtrip.as_view(),name='uploadtrip'),
    path('userquery/',views.userquery.as_view(),name='userquery'),
    path('reply/<slug:id>',views.reply.as_view(),name='reply'),
    # path('uploadpackage/',views.uploadpackage.as_view(),name='uploadpackage'),





    

]

ToursApp/models.py
from django.db import models

# Create your models here.

class DestinationModel(models.Model):
    destination = models.CharField(max_length=100,primary_key=True)
    dphoto = models.ImageField(blank=True,upload_to='dphotos/')
    dinfo = models.TextField(blank=True,default=0)
    
    def __str__(self):
        return self.destination

class PackageModel(models.Model):
    tour_id = models.CharField(primary_key=True,max_length=100)
    destination = models.ForeignKey(DestinationModel,on_delete=models.CASCADE)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    place_info = models.TextField(blank=True)
    places = models.ImageField(upload_to='places/' , blank=True)
    places1 = models.ImageField(upload_to='places/' , blank=True)
    places2 = models.ImageField(upload_to='places/' , blank=True)
    places3 = models.ImageField(upload_to='places/' , blank=True)
    from_date = models.DateField()
    to_date = models.DateField()
    day_one = models.TextField(blank=True)
    day_two = models.TextField(blank=True)
    day_three = models.TextField(blank=True)
    day_four = models.TextField(blank=True)
    day_five = models.TextField(blank=True)
    tour_info = models.TextField(blank=True)
    from_location = models.CharField(max_length=100)
    to_location = models.CharField(max_length=100)
    price = models.IntegerField()
    meet_time = models.DateTimeField()
    cancel_policy = models.CharField(max_length=100)
    numdays = models.IntegerField(blank=True,default=0)



class ProfileModel(models.Model):
    username = models.CharField(primary_key=True,max_length=100)
    contact = models.CharField(max_length=100)
    address = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.username
        

class BookingModel(models.Model):
    bookid = models.CharField(primary_key=True,max_length=100)
    tour_id = models.CharField(max_length=100)
    user_name = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    from_location = models.CharField(max_length=100)
    to_location = models.CharField(max_length=100)
    price = models.IntegerField()
    numdays = models.IntegerField()
    payment_method = models.CharField(max_length=100)
    created_at = models.DateField(auto_now=True)
    status = models.CharField(max_length=100,default='Active')
    people = models.IntegerField(blank=True)


class TripStoryModel(models.Model):
    storytype = models.CharField(max_length=100,default='userstory')
    username =models.CharField(max_length=100)
    image = models.ImageField(upload_to='stories/', blank=True)
    desc = models.TextField(blank=True)
    created_at = models.DateField(auto_now=True)


class ContactUsModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    feedback = models.TextField()
    reply= models.TextField(blank=True)
    

ToursApp/views.py
from django.views import View
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm,ProfileForm,BookingForm,tripstoryform,ContactUsForm
from .models import PackageModel,DestinationModel,ProfileModel,BookingModel,TripStoryModel , ContactUsModel
from django.contrib.auth.models import User
from django .contrib.auth import authenticate, login, logout
from django.contrib import messages
import random as r
import re



# Create your views here.


class home(View):
    def get(self, request):
        data1 = PackageModel.objects.all()[0:4]

        
        context = {'data1':data1}
        return render(request,'ToursApp/home.html',context)

class register(View):
    def get(self,request):
        forms=RegisterForm()
        context={'forms':forms}
        return render(request,'ToursApp/register.html',context)

    def post(self,request):
        forms=RegisterForm()
        if request.method == 'POST':
            forms=RegisterForm(request.POST)
            if forms.is_valid():
                messages.success(request,'Successfully User Registered')
                forms.save()
                # messages.success(request,'Successfully User Registered')
                return redirect('home')
        
        context={'forms':forms}

        return render(request,'ToursApp/register.html',context)
    
class signin(View):
    def get(self,request):
        
        forms=LoginForm()
        context={'forms':forms}
        return render(request,'ToursApp/signin.html',context)

    def post(self,request):
        if request.method == 'POST':

            username= request.POST['username']
            pass1= request.POST['password']

            user= authenticate(username=username, password=pass1)

            if user is not None:

                if username == 'admin':

                    login(request,user)
                    messages.success(request,f'Successfully User {username} Logged in..')
                    return redirect('home')

                else:

                    login(request,user)
                    messages.success(request,f'Successfully User {username} Logged in..')
                    return redirect('home')

            else:

                messages.warning(request,'😔 Something Went Wrong..!!')
                forms=LoginForm()
                context={'forms':forms}
                return render(request,'ToursApp/signin.html',context)


        messages.warning(request,'😔 Something Went Wrong..!!')
        return render(request,'ToursApp/signin.html',context)

class destination(View):
    def get(self,request):
        data= DestinationModel.objects.all()
        print(data)
        data1 = PackageModel.objects.all()
        context = {'data1':data1,'data':data}
       
        return render(request,'ToursApp/destination.html',context)


class state(View):
    def get(self,request,destination):
        data = DestinationModel.objects.all()
        cat=DestinationModel.objects.get(destination=destination)
        data1 = PackageModel.objects.filter(destination=cat)

        context = {'data':data,'data1':data1}

        return render(request,'ToursApp/destination.html',context)





class viewdetail(View):
    def get(self,request,tour_id):

        if request.user.is_authenticated:
            try:

                data = PackageModel.objects.get(tour_id=tour_id)
                userdata = ProfileModel.objects.get(username=request.user)
                a=str(request.user)
                if userdata.username == a:
                    book_id = r.randint(10000000,99999999)
                    # form = BookingForm()
                    context = {'data':data,'book_id':book_id,'userdata':userdata} 
                    return render(request,'ToursApp/viewdetail.html',context)
                    
                else:
                    return redirect('home')


            except:
                messages.warning(request,'update profile')
                return render(request,'ToursApp/profile.html',{'username':request.user})
                
                
        else:
            messages.warning(request,'login now')
            return redirect('destination')


    def post(self,request,tour_id):
        if request.method == 'POST':
            price=request.POST['price']
            people=request.POST['people']
            user_name=request.POST['user_name']
            tour_id=request.POST['tour_id']
            book=request.POST['bookid']

            data=ProfileModel.objects.get(username=user_name)
            data1=PackageModel.objects.get(tour_id=tour_id)
            form=BookingForm()
            
            price=int(price)
            people=int(people)

            Total_amount=price*people

            context={'Total_amount':Total_amount,'data':data,'data1':data1,'book':book,'people':people ,'form':form}
            return render(request,'ToursApp/booking.html',context)



class booking(View):

    def get(self,request):
        return redirect('home')

    def post(self,request):
        print('enter')
        forms = BookingForm()
        book_id=request.POST['bookid']
        tour_id = request.POST['tour_id']
        if request.method == 'POST':
            print('post')
            forms = BookingForm(request.POST)
            if forms.is_valid():
                print('valid')
                messages.success(request, 'Booking successfully done.. is your booking id')
                forms.save()
                return redirect('home')

            else:
                print('invalid')
                messages.warning(request,'Something went wrong')
                return redirect('viewdetail',tour_id=tour_id)
        else:
            print('in')
            messages.warning(request,'Something went wrong')
            return redirect('viewdetail',tour_id=tour_id)
    



class mytrips(View):
    def get(self,request):
        data = BookingModel.objects.filter(user_name=request.user).values()
        e =[]

        for d in data:
            d=d.values()
            for c in d:
                e.append(c)

        try:
            data1 = e[2]

        except:

            data1 = str(e)

        userlogin = str(request.user)

        context={'data':data,'data1':data1,'userlogin':userlogin}
        return render(request,'ToursApp/mytrips.html',context)


class tripstory(View):
    def get(self,request):
        data = TripStoryModel.objects.filter(storytype = 'adminstory')
        data1 = TripStoryModel.objects.filter(storytype = 'userstory')
        userlogin = request.user
        
        form = tripstoryform()
        context = {'data':data,'data1':data1,'form':form,'userlogin':userlogin}
        return render(request,'ToursApp/tripstory.html',context)

    def post(self,request):

        form = tripstoryform()
        if request.method == 'POST':
            form = tripstoryform(request.POST,request.FILES)
            if form.is_valid():
                messages.success(request,'Story added')
                form.save()
                return redirect('tripstory')


            else:
                messages.success(request,'something went wrong')
                return redirect('home')







class cancelbook(View):
    def post(self,request,bookid):
        data=BookingModel.objects.get(bookid=bookid)
        data.delete()
        messages.success(request,'Booking Cancelled successfully')

        return redirect('mytrips')


class viewbooking(View):
    def get(self,request,tour_id):
        data = PackageModel.objects.filter(tour_id=tour_id)
        context = {'data':data}
        return render(request,'ToursApp/viewbooking.html',context)




def contactvalidate(contact):
        p=r'[6-9][0-9]{9}$'

        if re.match(p,contact):
            return True

        else:
            return False


class profile(View):
    def get(self,request,username):
        print(username)
        data = ProfileModel.objects.filter(username=request.user).values()
      
        e = []
        for d in data:
            c = d.values()

            for i in c:
                e.append(i)
        
        try:

            data1 = e[0]

        except:

            data1 = str(e)

        if data1 == username:
            forms = ProfileForm()
            # context={'forms':forms,'user':request.user,'data':data}
            context={'data':data}
            messages.success(request,'Profile Updated')
            # return render(request,'ToursApp/profile.html',context)
            return redirect('home')
            

        else:
            forms = ProfileForm()
            context={'forms':forms,'user':request.user}

            return render(request,'ToursApp/profile.html',context)


    def post(self,request,username):

        forms = ProfileForm()
        if request.method == 'POST':
            userlogin = request.user
            
            contact= request.POST['contact']
            d=contactvalidate(contact)
            print(d)

            if d == True:

                forms=ProfileForm(request.POST)
                if forms.is_valid():
                    messages.success(request,'Profile Updated Successfully')
                    forms.save()
                    return redirect('home')

                else:

                    context={'forms':forms,'user':request.user}
                    return render(request,'ToursApp/profile.html',context)
            else:
                messages.warning(request,'invalid number')
                return redirect('profile',username=userlogin)
        else:
            

templates/ToursApp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Boostrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Bootstrap Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'ToursApp/CSS/nav.css' %}">

    {% block css %}
    {% endblock css %}

    {% block js %}
    {% endblock js %}

    {% block title %}
    {% endblock title %}


</head>

<body>

    <div class="m-3">
        {% include 'ToursApp/nav.html' %}
    </div>

    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message}}<button type="button"
            class="float-end btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </p>
    {% endfor %}
    {% endif %}

   

    
    {% block body %}

    {% endblock body %}



</body>

</html>

templates/ToursApp/booking.html
{% extends 'ToursApp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'ToursApp/CSS/booking.css' %}">

<style>
#userid{
    margin: 10px;
    text-align: left;
    font-weight:bold;
    font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;        
}
#contact{

    
    text-align: right;
    text-align:left;
}
#card{
    
    margin-left: 100px;
    padding-left: 100px;
}


#main{
    background-image: url('/static/ToursApp/Images/joy2.jpeg');
    height: 800px;

}

#heading{

    color: black;
    padding-top: 50px;
    text-align: center;
    text-shadow:black;
    font-style:oblique ;
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-weight: bold;
}

#cardhead{

    font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
}

#date{
    font-weight: bold;
    font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;

}
#price{
    
    
    font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;

}

#people{

    font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    text-align: center; 
    padding-left: 50px;
    
    
}   

#pay{
 
    text-align: center;
    padding-left: 150px;
    padding-top: 25px;
}
</style>


{% endblock css %}

{% block js %}

<script>

function wanttobook() {

var ch = confirm('Are you sure you want to book?');

if (ch == true) {

    return true;

}

else {

    return false;
};

};

</script>

{% endblock js %}

{% block title %}
<title>Booking Page</title>
{% endblock title %}


{% block body %}
<div id="main">
<div class="container text-center">
    
    <h1 id="heading"><img src="{% static 'ToursApp/Images/diwali.gif' %}" height="70px" alt="">Book Now..Unknown lands await you..!<img src="{% static 'ToursApp/Images/diwali.gif' %}" height="70px" alt=""></h1>
    <!-- card -->
    <div class="row">

        <div class="col-4" id="card">
            <div class="card shadow-lg border m-5" style="width: 50rem;" >
               
                <div class="card-body">
                    <h5 class="card-title" id="cardhead">{{data1.destination}} > {{data1.city}}</h5>
                    <div class="card-text">

                        <form action="{% url 'booking' %}" method="post" onsubmit="return wanttobook()">
                            {% csrf_token %}


                            <label for="id_bookid"></label>
                            <input type="text" name="bookid" maxlength="100" value="{{book}}" hidden required
                                id="id_bookid">



                            <label for="id_tour_id"></label>
                            <input type="text" name="tour_id" maxlength="100" value="{{data1.tour_id}}" hidden required
                                id="id_tour_id">


                            <div class="row">
                            <div class="my-2 mt-0 m-5 text-start" id="userid">
                                <label for="id_user_name">User Name</label>
                                <input type="text" maxlength="100" value="{{data.username}}" disabled>
                                <input type="text" name="user_name" maxlength="100" value="{{data.username}}" hidden
                                    required id="id_user_name">
                            

                        

                        

                            <!-- <div class="my-2 mt-0 mb-5 pb-5 text-end" id="contact"> -->
                                <label for="id_contact" class="mt-0">Contact Number</label>
                                <input type="text" maxlength="100" value="{{data.contact}}" disabled>
                                <input type="text" name="contact" maxlength="100" value="{{data.contact}}" hidden
                                    required id="id_contact">
                            <!-- </div> -->
                        </div>
                        </div>

                            <div class="my-2" id="date">
                                <label for="">{{data1.from_date}}</label>
                                <label for="">---to---</label>
                                <label for="">{{data1.from_date}}</label>
                            </div>

                            <div class="my-2">
                                <label for="id_from_location">{{data1.from_location}}</label>
                                <input type="text" name="from_location" value="{{data1.from_location}}" maxlength="100"
                                    hidden required id="id_from_location">


                                <label for="">---to---</label>

                                <label for="id_to_location">{{data1.to_location}}</label>
                                <input type="text" name="to_location" value="{{data1.to_location}}" maxlength="100"
                                    hidden required id="id_to_location">
                            </div>


                            <div class=" m-5 text-start" id="price">
                                <label for="id_price">Price: <i class="bi bi-currency-rupee"></i> {{Total_amount}}</label>
                                <!-- <input type="number" value="{{Total_amount}}" disabled> -->
                                <input type="number" name="price" value="{{Total_amount}}" hidden required
                                    id="id_price">
                            

                          
                            <!-- <div class="my-2 mb-0 text-end " id="price"> -->
                                <label for="id_numdays" class="ms-5">Number of Days: {{data1.numdays}}</label>
                                <!-- <input type="number" value="{{data1.numdays}}" disabled> -->
                                <input type="number" name="numdays" value="{{data1.numdays}}" hidden required
                                    id="id_numdays">
                            <!-- </div> -->


                            


                            <!-- <div class="my-2 mt-0 ms-0  text-start" > -->
                                <label for="id_people" id="people">people: {{people}}</label>
                                <input type="text" name="people" value="{{people}}" hidden id="id_people">
                                <!-- <input type="text" name="people" value="{{people}}" disabled id="id_people"> -->
                            

                            

                             <!-- <div class="my-5" > -->
                                <label for="id_payment_method" id="pay" >Payment_Method:</label>
                                <input type="text" name="payment_method" maxlength="100" placeholder="Enter UPI id" required
                                    id="id_payment_method">
                            </div>

                            <label for="id_status"></label>
                            <input type="text" name="status" value="Active" maxlength="100" hidden required
                                id="id_status">

                            <!-- <button type="submit" class="btn btn-outline-warning text-dark">book</button> -->
                            <input type="submit" class="btn btn-outline-warning text-dark" value="book">
                            <button class="btn btn-outline-secondary"><a href="{% url 'destination' %}"
                                    class="text-decoration-none text-dark">Cancel</a></button>
                        </form>
                    </div>

                </div>

            </div>
            

        </div>
        
    </div>

    

    



    </div>
</div>
{% endblock body %}

templates/ToursApp/contactus.html
{% extends 'ToursApp/base.html' %}
{% load static %}

{% block css %}
<style>
    #main {

        height: 650px;
        position: relative;
    }

    #divhead{
        background-image: url('/static/ToursApp/Images/contact.webp');

        box-shadow: 8px white;
        color: white;
        padding: 50px;
        width:1200px;
        height: 700px;
    }

    #form{
        margin-top: 50px;
        margin-left: 150px;
        padding-left: 150px;
        width: 600px;
        
    }

    #label{

        padding: 5px;
        margin: 5px;
    }

</style>

{% endblock css %}

{% block js %}
{% endblock js %}

{% block title %}
<title>Contact Us</title>
{% endblock title %}


{% block body %}

<div id="main">
    <div class="container" id="divhead">
        {% if user.is_authenticated is False %}
        <form action="{% url 'contactus' %}" method="post" id="form" class="shadow-lg rounded-3">
            {% csrf_token %}


            <label for="id_name" id="label">Enter Your Name:</label>
            <input type="text" name="name" class="form-control" maxlength="100" required id="id_name">


            <label for="id_email" id="label">Enter Your Email:</label>
            <input type="email" name="email" class="form-control" maxlength="254" required id="id_email">


            <label for="id_feedback" id="label">Enter Your Feedback Or any Query:</label>
            <textarea name="feedback" cols="40" rows="10" class="form-control" required id="id_feedback"></textarea>


            <label for="id_reply" id="label"></label>
            <textarea name="reply" cols="40" rows="10" class="form-control" hidden id="id_reply"></textarea>


            <div class="text-center">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
        </form>
    </div>

    {% else %}
    <div class="container" id="divhead">
        <form action="{% url 'contactus' %}" method="post" class="shadow-lg rounded-3">

            {% csrf_token %}

            <label for="id_name" id="label">Enter Your Name:</label>
            <input type="text" name="name" value="{{user.username}}" class="form-control" maxlength="100" required
                id="id_name" hidden>
            <input type="text" value="{{user.username}}" class="form-control" maxlength="100" disabled>


            <label for="id_email" id="label">Enter Your Email:</label>
            <input type="email" name="email" value="{{user.email}}" class="form-control" maxlength="254" required
                id="id_email" hidden>
            <input type="email" value="{{user.email}}" class="form-control" maxlength="100" disabled>

            <label for="id_feedback" id="label">Enter Your Feedback Or any Query:</label>
            <textarea name="feedback" cols="40" rows="10" class="form-control" id="id_feedback"></textarea>

            <label for="id_reply" id="label"></label>
            <textarea name="reply" cols="40" rows="10" class="form-control" hidden id="id_reply"></textarea>

            <div class="text-center">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
        </form>
    </div>

    {% endif %}
</div>
{% endblock body %}

templates/ToursApp/profile.html
{% extends 'ToursApp/base.html' %}
{% load static %}

{% block css %}

{% endblock css %}

{% block js %}
{% endblock js %}

{% block title %}
<title>Register Page</title>
{% endblock title %}


{% block body %}
<div>
<div class="container shadow rounded-3">

<form action="{% url 'profile' user.username %}" method="post">
    {% csrf_token %}
    <div class="text-dark my-3 pt-5">
        <label for="id_username">Enter Username:</label>
        <input type="text" name="username" class="form-control" value="{{user.username}}" hidden maxlength="100" required id="id_username">
        <input type="text" class="form-control" value="{{user.username}}" disabled maxlength="100">

        </div>
        
        <div class="text-dark my-3">
        <label for="id_contact">Update Contact Number:</label>
        <input type="text" name="contact" class="form-control" maxlength="100" placeholder="{{data.contact}}" required id="id_contact">
        </div>
        
        <div class="text-dark my-3">
        <label for="id_address">Update Your Address:</label>
        <textarea name="address" cols="40" rows="10" class="form-control" placeholder="{{data.address}}" required id="id_address"></textarea>
        </div>
        
        <div class="text-dark my-3">
        <label for="id_email">Email-ID:</label>
        <input type="email" name="email" value="{{user.email}}" class="form-control" maxlength="254" hidden required id="id_email">
        <input type="email"  value="{{user.email}}" class="form-control" maxlength="254" disabled>
        </div>
        
        <div class="container text-center mt-5 pb-5">
            <button type="submit" class="btn btn-success">Submit</button>
            <button class="btn btn-secondary"> <a href="{% url 'home' %}" class="text-decoration-none text-light"> Back </a></button>

        </div>

</form>
</div>
</div>
{% endblock body %}

templates/ToursApp/uploadpackage.html
<!-- {% extends 'ToursApp/base.html' %}
{% load static %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

{% block title %}
<title>upload</title>
{% endblock title %}


{% block body %}
<div class="container shadow-lg mt-5">
    <form action="{% url 'uploadpackage' %}" method="post" enctype="multipart/form-data"  id="form">
        {% csrf_token %}
{% for d in form %}

{{d.label_tag}}
{{d}}


{% endfor %}

<input type="submit" value="submit" class="btn btn-info mt-3 mb-3">
</form>
</div>



{% endblock body %} -->

templates/ToursApp/userquery.html
{% extends 'ToursApp/base.html' %}
{% load static %}

{% block css %}
<style>
    #main{
        background-image: url('/static/ToursApp/Images/bagr5.jpg');
        height: 1000px;
    }

    #card{

        margin-top: 20px;

        
    }
</style>
{% endblock css %}

{% block js %}
{% endblock js %}

{% block title %}
<title>user Queries</title>
{% endblock title %}


{% block body %}
<div id="main">
{% for d in data %}
<div class="pt-3">
    <div class="card mt-3 ms-5" style="width: 35rem;" id="card">
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <h5 class="card-title">{{d.name}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{d.email}}</h6>
                    <p class="card-text">{{d.feedback}}</p>
                </div>
                <div class="col-6">
                    <form action="{% url 'reply' d.id %}" method="post">
                        {% csrf_token %}


                        <label for="id_reply"></label>
                        <textarea name="reply" cols="40" rows="10" class="form-control" placeholder="Reply to User" id="id_reply"></textarea>


                        <input type="submit" value="Submit" class="btn btn-primary mt-3">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
</div>

{% endblock body %}